# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - ubuntu1804.wsl:22122
  web-server-url: http://ubuntu1804.wsl:8888/
server:
  port: 9999
spring:
  servlet:
    multipart:
      #  java.lang.IllegalStateException:
      # org.apache.tomcat.util.http.fileupload.impl.FileSizeLimitExceededException:
      # The field file exceeds its maximum permitted size of 1048576 bytes.] with root cause
      max-file-size: 10MB
      max-request-size: 200MB
